# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewMyip < Formula
  desc "Determine your Internet-facing IP address and location from multiple sources."
  homepage "https://github.com/bengarrett/myip/"
  version "0.9.2-fix5"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/bengarrett/homebrew-myip/releases/download/v0.9.2-fix5/homebrew-myip_macOS_Intel.tar.gz"
    sha256 "f965ad8ed1db2d706d68bfd2f91c0fd35cae45018f70a7816f21d913de4ce774"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/bengarrett/homebrew-myip/releases/download/v0.9.2-fix5/homebrew-myip_macOS_M-series.tar.gz"
    sha256 "0bd2d2cb10e66fc0800a11c7582fe5215baa0b90b14c2a23656a911313afd6d4"
  end

  def install
    bin.install "myip"
  end
end
