# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewMyip < Formula
  desc "Determine your Internet-facing IP address and location from multiple sources."
  homepage "https://github.com/bengarrett/myip/"
  version "0.9.2-fix4"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/bengarrett/homebrew-myip/releases/download/v0.9.2-fix4/homebrew-myip_macOS_Intel.tar.gz"
    sha256 "e21b5d8b4eb3aebf5559afae69bcbc07e2df241a64f5771ebf7a8ffa7e67a38b"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/bengarrett/homebrew-myip/releases/download/v0.9.2-fix4/homebrew-myip_macOS_M-series.tar.gz"
    sha256 "b8960b2670256fc368002567087fd83710948bb545f0acfee4f11b88883037c2"
  end

  def install
    bin.install "homebrew-myip"
  end
end
