# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myip < Formula
  desc "Determine your Internet-facing IP address and location from multiple sources."
  homepage "https://github.com/bengarrett/myip/"
  version "1.1.0"
  license "MIT"
  depends_on :macos

  on_macos do
    url "https://github.com/bengarrett/homebrew-myip/releases/download/v1.1.0/homebrew-myip_macOS_all.tar.gz"
    sha256 "de1e0395985dc5325e2310dff080e0376451681d701bb19af9d0c6a9907b69bc"

    def install
      bin.install "myip"
    end
  end

  test do
    system "#{bin}/myip --version"
  end
end
