# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myip < Formula
  desc "Determine your Internet-facing IP address and location from multiple sources."
  homepage "https://github.com/bengarrett/myip/"
  version "0.9.2-fix3"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/bengarrett/homebrew-myip/releases/download/v0.9.2-fix3/homebrew-myip_macOS_Intel.tar.gz"
    sha256 "6633a0476b6692494172ca794308b7bb7be78afe43df55db727b6b22f3fd1c96"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/bengarrett/homebrew-myip/releases/download/v0.9.2-fix3/homebrew-myip_macOS_M-series.tar.gz"
    sha256 "85bb6343ab4dc61cf483c297f2167b94ea8ac72f79cda24ce2016e89d54b7cee"
  end

  def install
    bin.install "homebrew-myip"
  end
end
